require("prototypes.techs")
require("prototypes.mining")
require("prototypes.furnace")
require("prototypes.energy")
require("prototypes.assemblers")
require("prototypes.small_electric_pole")
require("prototypes.steel_chest")
